name: Healthy Bites CI

on:
  push:
    branches:
      - desarrollar
      - maestro
  pull_request:
    branches:
      - desarrollar
      - maestro

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run JUnit tests
        run: mvn test
